Repository hugovk/norwegianblue, pull requests merged in 2023-11, with the labels that each got.

#176 Apply colour to HTML output
  .coveragerc
  .pre-commit-config.yaml
  README.md
  pyproject.toml
  src/norwegianblue/__init__.py
  src/norwegianblue/cli.py
  tests/data/expected_output.py
  tox.ini
Labels: changelog: Added

#177 Add support for Python 3.13
  .github/workflows/test.yml
  pyproject.toml
  tox.ini
Labels: changelog: Added

#178 Show deprecation warning in `--help` in yellow
  README.md
  src/norwegianblue/cli.py
Labels: changelog: skip

#179 Document installation using pipx
  README.md
Labels: changelog: Added

#180 Use hynek/build-and-inspect-python-package for releasing
  .flake8
  .github/workflows/deploy.yml
  .github/workflows/labels.yml
  .github/workflows/lint.yml
  .github/workflows/require-pr-label.yml
Labels: changelog: skip

#181 Add some more type hints
  .pre-commit-config.yaml
  scripts/run_command.py
  src/norwegianblue/__init__.py
  src/norwegianblue/_cache.py
  src/norwegianblue/_data.py
  tests/test_norwegianblue.py
Labels: changelog: Added

#182 Fix `KeyError` after 'Did you mean?' correction
  src/norwegianblue/cli.py
Labels: changelog: Fixed
