Repository hugovk/norwegianblue, pull requests merged in 2024-01, with the labels that each got.

#190 Disable colour to fix CI
  tests/test_norwegianblue.py
Labels: testing, changelog: skip

#189 Fix IndexError when there are no suggestions
  src/norwegianblue/__init__.py
  src/norwegianblue/cli.py
  tests/test_norwegianblue.py
Labels: changelog: Fixed

#191 Colorize "extended support" column and re-order date columns
  src/norwegianblue/__init__.py
  tests/data/expected_output.py
  tests/data/sample_response.py
  tests/test_norwegianblue.py
Labels: changelog: Added
